allure:
  token_env: ALLURE_TOKEN
  url: ALLURE_URL
columns:
  automated: automated
  description: description
  expected_result: expected_result
  lead: Lead
  name: Name
  owner: Owner
  precondition: Precondition
  scenario: scenario
  tag: tag
custom_fields:
- custom_field_id: -2
  custom_field_name: Feature
  id: 5162
  name: TEST IMPORT FEATURE FOLDER
project:
  id: 34
